# use vi mode in copy mode
set-window-option -g mode-keys vi

# put statusbar top
set-option -g status-position top

# Keybinding for sending prefix
set -g prefix C-a
unbind-key C-b
bind-key C-a send-prefix

# Keybinding for spliting window
unbind %
bind | split-window -h
unbind '"'
bind - split-window -v

# Keybinding for moving cursor
bind h select-pane -L
bind j select-pane -D
bind k select-pane -U
bind l select-pane -R

# Shift-movement keys will resize panes
bind -r H resize-pane -L 5
bind -r J resize-pane -D 5
bind -r K resize-pane -U 5
bind -r L resize-pane -R 6

# Bind to reload config
bind r source-file ~/.tmux.conf

# Pane settings
set -g status-left-length 90
set -g status-right-length 90
#set -g status-left '[#(whoami)]'
set -g status-left '[Dont talk to me, now!]'
set -g status-right '#[fg=green][#(date +" %m-%d %H:%M ")]'
set -g status-justify "centre"
set -g window-status-format '#I #W'
set -g window-status-current-format ' #I #W '

# https://github.com/seebi/tmux-colors-solarized
#### COLOUR (Solarized 256)

# default statusbar colors
set-option -g status-bg colour236
set-option -g status-fg colour144
set-option -g status-attr default

# default window title colors
set-window-option -g window-status-fg colour255
set-window-option -g window-status-bg default
set-window-option -g window-status-attr dim

# active window title colors
set-window-option -g window-status-current-fg white
set-window-option -g window-status-current-bg colour208
set-window-option -g window-status-current-attr bright

# pane border
set-option -g pane-border-fg green
set-option -g pane-border-bg black
set-option -g pane-active-border-fg red
set-option -g pane-active-border-bg black

# message text
set-option -g message-bg white
set-option -g message-fg black
set-option -g message-attr bright

# pane number display
set-option -g display-panes-active-colour colour33 #blue
set-option -g display-panes-colour colour166 #orange


# tmux manage prefix
set -g @prefix_highlight_fg 'white'
set -g @prefix_highlight_bg 'blue'
set -g status-right '#{prefix_highlight} | %a %Y-%m-%d %H:%M'
set -g status-right "Online: #{online_status} | %a %h-%d %H:%M "
